/*
	Problem 2

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	Find the sum of all the even-valued terms in the sequence which do not exceed four million.
*/

#include "../../Src/Headers/libEuler.h"

#define N 4000000

unsigned int P0002(void){
    unsigned int sum=0,fibonacci=3,numPrev[2]={1,2};
    while(TRUE){
    	fibonacci=numPrev[0]+numPrev[1];
    	if(fibonacci%2==0 && fibonacci < N) sum+=fibonacci;
    	numPrev[0]=numPrev[1];
        numPrev[1]=fibonacci;
    	if(fibonacci >= N) break;
    }
    return sum;
}
