/*
	Problem 29

	Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    22=4, 23=8, 24=16, 25=32
    32=9, 33=27, 34=81, 35=243
    42=16, 43=64, 44=256, 45=1024
    52=25, 53=125, 54=625, 55=3125

	If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

	4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

	How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

	8 oct. 2018
 */

#include "../../Src/Headers/libEuler.h"
#define A 100
#define B 100

double vResult[A*B]={0};
long int count=0;
int search_value(double pows){
	for(int i=0;vResult[i]!=0;i++){
		if(vResult[i]==pows) return FALSE;
	}
	vResult[count]=pows;
	count++;
	return TRUE;
}

void P0029(void){
	time_t tInit=clock();
	double result=0;
	for (int i =2; i<=A;i++){
		for(int j=2;j<=B;j++){
			if(search_value(pow(i,j))) result++;
		}
	}
	time_t tEnd=clock();
	printf("Problem 29 - Result: %.0f. Elapsed Time: %.6f\n", result,(double) (tEnd-tInit)/CLOCKS_PER_SEC);
	return;
}
