/*
	Triangular, pentagonal, and hexagonal
	Problem 45

	Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

	Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
	Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
	Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

	It can be verified that T285 = P165 = H143 = 40755.

	Find the next triangle number that is also pentagonal and hexagonal.

	25 dic. 2018
 */

#include "../../Src/Headers/libEuler.h"

lu p(int nGonal, lu n){
	return (nGonal - 2) * n * (n - 1) / 2 + n;
}

void P0045(void){
	time_t tInit=clock();
	lu hexagonal, pentagonal;
	for(lu i=166; ;i++){
		pentagonal=p(5,i);
		for(lu j=1;j<=i;j++){
			hexagonal=p(6,j);
			if(hexagonal==pentagonal){
				time_t tEnd=clock();
				printf("Problem 45 - Result: %lu. Elapsed Time: %.6f\n",hexagonal ,(double) (tEnd-tInit)/CLOCKS_PER_SEC);
				return;
			}
		}
	}
	return;
}
