/*
Large sum
Problem 12
v2

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

29 abr. 2018/23:46:05
*/

#include "libEuler.h"

#define N 500
#define cantP 2000

void P0012(void){
    time_t tInit=clock();
    int n=3,dn=2,cont=0,n1=0,dn1=0,i=0,exponent=0;
    Vector *vPrimes;
    vInit(&vPrimes);
    generate_vector_of_primes(vPrimes,cantP);
    while(cont<=N){
    	n++;
    	n1=n;
    	if(n1%2==0) n1/=2;
    	dn1=1;
    	vFirst(vPrimes);
    	for(i=0;i<cantP;i++,vNext(vPrimes)){
    		if(vGetValue(vPrimes)*vGetValue(vPrimes)>n1){
    			dn1*=2;
    			break;
    		}
    		exponent=1;
    		while(n1%vGetValue(vPrimes)==0){
    			exponent++;
    			n1/=vGetValue(vPrimes);
    		}
    		if(exponent>1) dn1*=exponent;
    		if(n1==1) break;
    	}
    	cont=dn*dn1;
    	dn=dn1;
    }
    time_t tEnd=clock();
    printf("Problem 12 - Result: %llu. Elapsed Time: %.6f\n", triangle_number(n),(double) (tEnd-tInit)/CLOCKS_PER_SEC);
    return;
}
