/*
	Pentagon numbers
	Problem 44

	Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

	1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

	It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

	Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

	25 dic. 2018
 */

#include "libEuler.h"
#define N 2500

int isPentagonal(llu n){
	double resp=(sqrt(24.0 * n + 1.0) + 1.0) / 6.0;
	if(resp==floor(resp)) return TRUE;
	return FALSE;
}

void P0044(void){
	time_t tInit=clock();
	llu vPentagonals[N]={0};
	llu sum=0, dif=0;
	for(int i=1;i<N;i++) vPentagonals[i]=i*(3*i-1)/2;
	for(int i=1;i<N;i++){
		for(int j=i+1;j<N;j++){
			sum=vPentagonals[i] + vPentagonals[j];
			if(isPentagonal(sum)==TRUE){
				dif=vPentagonals[j] - vPentagonals[i];
				if(isPentagonal(dif)==TRUE){
					clock_t tEnd = clock();
					printf("Problem 44 - Result: %llu. Elapsed Time: %.6f\n", dif,(double) (tEnd-tInit)/CLOCKS_PER_SEC);
					return;
				}
			}
		}
	}
	return;
}
